---
- name: create jenkins server
  hosts: jenkins
  remote_user: root
  tasks: 
  - name: update system
    yum: 
      name: "*" 
      state: latest
  - name: install git
    yum: 
      name: git
      state: present
  - name: install java11
    command: amazon-linux-extras install java-openjdk11 -y
  - name: adding repo 
    yum_repository:
      description: jenkins
      name: Jenkins 
      baseurl: http://pkg.jenkins.io/redhat
      gpgcheck: no
  - name: Import a key from a url
    rpm_key:
      state: present
      key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
  - name: install jenkins
    yum:
      name: jenkins
      state: latest
  - name: start jenkins
    systemd:
      state: started
      name: jenkins
      enabled: yes
  - name: Set a hostname
    hostname:
      name: jenkins
