---
- name: install k8s server
  hosts: k8s-master
  remote_user: root
  tasks: 
  - name: update system
    yum:
      name: "*"
      state: latest
  - name: Set a hostname
    hostname:
      name: k8s-master
  - name: install git
    yum: 
      name: git
      state: present
  - name: install java11
    command: amazon-linux-extras install java-openjdk11 -y
  - name: install docker
    yum: 
      name: docker
      state: present
  - name: start docker
    systemd:
      state: started
      name: docker
      enabled: yes
  - name: Enable repository
    yum_repository:
      name: kubernetes
      description: kubernetes
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      gpgcheck: yes
      gpgkey: 
        - https://packages.cloud.google.com/yum/doc/yum-key.gpg 
        - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude:
        - kubelet 
        - kubeadm 
        - kubectl
  - name: install kubelet kubeadm kubectl
    yum:
      name: 
        - kubelet 
        - kubeadm 
        - kubectl
      disable_excludes: kubernetes
  - name: Enable kubelet
    systemd:
      name: kubelet
      enabled: yes
  - name: initialize the cluster
    shell: kubeadm init 
    register: result
    until: result.stdout.find("Your Kubernetes control-plane has initialized successfully!") != -1
    retries: 5
    delay: 20
  - name: Create a directory 
    file:
      path: $HOME/.kube
      state: directory
  - name: Copy file with owner and permissions
    copy: 
      src: /etc/kubernetes/admin.conf
      dest: $HOME/.kube/config
      remote_src: yes
  - name: cni install weave
    shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  - name: generate kube token
    shell: kubeadm token create --print-join-command 
    register: kubetoken
  - name: Register dummy host with variable
    add_host:
        name: "DUMMY_HOST"
        kubetoken: " {{ kubetoken.stdout }}"
